-- ====================================================================
-- THEORY & CONCEPT:
-- Duplicates occur when multiple rows share identical values in key columns. We group the rows using GROUP BY on those columns and filter the groups using HAVING COUNT(*) > 1.
--
-- COMPLEXITY:
-- Time Complexity: O(N) to group rows.
-- Space Complexity: O(U) where U is the number of unique groups.
--
-- INTERVIEW Q&A:
-- Q: What is the difference between WHERE and HAVING?
-- A: WHERE filters rows before any grouping is performed. HAVING filters the summarized groups generated by the GROUP BY clause.
--
-- Q: Can you find duplicates using window functions?
-- A: Yes, by generating ROW_NUMBER() partitioned by duplicate keys, and selecting rows where row number > 1.
-- ====================================================================

-- SQL Query to find duplicate records in a table
-- Table Schema: Users(id, email, username)
-- We define duplicates based on the 'email' column.

SELECT email, COUNT(email) as occurrences
FROM Users
GROUP BY email
HAVING COUNT(email) > 1;
